export const SET_LOCATION_TEXT_INPUT = 'SET_LOCATION_TEXT_INPUT';
export const SET_LOCATION_RADIO_INPUT = 'SET_LOCATION_RADIO_INPUT';
export const SET_DEFAULT_INPUT = 'SET_DEFAULT_INPUT';
export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const LOADING_WEATHER_DATA = 'LOADING_WEATHER_DATA';
export const LOADED_WEATHER_DATA = 'LOADED_WEATHER_DATA';
export const ERROR_WEATHER_DATA = 'ERROR_WEATHER_DATA';
